### ISSUE TITLE
Sometimes failed to deploy service when creating multiple services at the same time: database is locked

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1216]
**Describe the bug**

**Steps to reproduce**
1. Setup a walrus service by docker.
2. Create 100 services at the same time.

**Result**

1. Some services failed to deploy: `database is locked`.
<img width="901" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/b9839618-de7f-44e9-a0ca-17a5e90e6afb">

```
2023-08-28T11:16:28.754Z	E	api	error requesting PUT /v1/projects/475928299931959298/environments/475955139920789506/services/475955286503325698/upgrade: 1 error occurred:
	* failed to apply service: rpc error: code = Unknown desc = database is locked


github.com/seal-io/walrus/pkg/apis/runtime.erroring
	github.com/seal-io/walrus/pkg/apis/runtime/middleware_error.go:45
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/seal-io/walrus/pkg/apis/runtime.recovering
	github.com/seal-io/walrus/pkg/apis/runtime/middleware_recovery.go:39
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/seal-io/walrus/pkg/apis/runtime.observing
	github.com/seal-io/walrus/pkg/apis/runtime/middleware_observation.go:89
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
github.com/seal-io/walrus/pkg/apis/runtime.(*Router).ServeHTTP
	github.com/seal-io/walrus/pkg/apis/runtime/router.go:191
net/http.serverHandler.ServeHTTP
	net/http/server.go:2947
net/http.initALPNRequest.ServeHTTP
	net/http/server.go:3556
net/http.(*http2serverConn).runHandler
	net/http/h2_bundle.go:5910
```

**Expected behavior**

**Environment**
- Walrus version: dev-f1eb375

**Additional context**

**Comment by thxCode** [comment]
the root cause is using an external K3s cluster that starts with a SQLite datastore: `curl -sfL https://get.k3s.io/ | INSTALL_K3S_EXEC="--tls-san ..." sh -s -`. modify the K3s cluster starting arguments with `curl -sfL https://get.k3s.io/ | INSTALL_K3S_EXEC="--cluster-init --etcd-disable-snapshots --disable=traefik,servicelb,metrics-server --disable-cloud-controller --disable-network-policy --disable-helm-controller --flannel-backend=host-gw  --node-name=local --kubelet-arg=system-reserved=cpu=300m,memory=256Mi  --kubelet-arg=kube-reserved=cpu=200m,memory=256Mi --tls-san ..." sh -s -`, and try again this. @Finenyaco

**Comment by Finenyaco** [comment]
After using embedded etcd, cannot reproduce `database is locked`. But the apiserver of k3s cluster with etcd datastore may easily crash when creating a large number of services at the same time.
