### ISSUE TITLE
Cannot automatically update access endpoints

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1443]
**Describe the bug**

**Steps to reproduce**
1. Create a service.
2. Go to the service details page and watch the access endpoints list.

**Result**

1. The access endpoints list is not updated automatically.

<img width="2490" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/5443a2d5-671b-4a63-952b-849a682fac1b">

2. Check the chunk request messages, no access endpoints updates.
<img width="1877" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/2a2e19eb-f088-49e3-96d5-c3e468c6d382">

3. After refreshing the page manually.
<img width="2486" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/c3bbf43b-4cde-417b-b05a-ba6378b846a3">

**Expected behavior**

**Environment**
- Walrus version: 4465aa8deb63ff1ceb270b6cbc1c5ae2852d8242
- UI version: dev-4eab774

**Additional context**

**Comment by alexcodelf** [comment]
The Reason is that endpoints of resource is fetched by operator when execute cronjob to discover resource components. But the endpoint stream subscribe `ResourceRevision`, once the revision output does not contains any output and resource conponment update task finished after contab job, the output will not update.

**Comment by gitlawr** [comment]
It worked in v0.3.1

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 2ef0df227f0580311686bc6ae2ab19a9548bee94
- UI version: dev-6e415a8

**Test Result:** pass
