### ISSUE TITLE
Add system labels for environments related to available connectors

### ISSUE THREAD

**Issue by gitlawr** [seal-io/walrus#1757]
**Is your enhancement related to a problem? Please describe.**
Maintain the system labels for environments related to available connectors. It helps to set matching rules in resource definitions.

e.g., `walrus.seal.io/provider-aws=true`

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a32da81f4a08410f854d9897f88885b7a5dc63fd
- UI version: dev-98d0e3e

**Test Result:** 

- Add labels: pass
- UI: Can it display the complete key? Because the prefixes for the labels are all the same. Users cannot easily discern what the label is at a glance.

<img width="1207" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/333cbf69-0cb4-485e-a082-fbad533eed5e">

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 8ff16bfe4326036642753b1ba895fa5b0e3b1791
- UI version: dev-7590f46

**Test Result:** pass
- UI:
<img width="831" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6b194520-650a-4a9b-87b1-97b9e993220f">

- When cloning an environment, built-in labels will be added or removed based on the connectors added to the environment.
