### ISSUE TITLE
Failed to deploy Alicloud RDS when configuring replication and publicly accessible simultaneously

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2079]
**Describe the bug**

**Steps to reproduce**
1. Create a Alibaba connector and add to an environment.
2. Create a resource using template `alicloud-rds-mysql v0.2.0`.
3. Set 'Architecture' to 'replication' and set 'Publicly Accessible' to true simultaneously.

<img width="1982" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/6ced4944-867d-4ddb-b517-a9f8c06d398c">
<img width="2407" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/1ad627b7-9335-43b2-bed3-45172336fc3a">

**Result**

1. Failed to deploy.
<img width="883" alt="image" src="https://github.com/seal-io/walrus/assets/26084756/fb2580dc-da92-4c67-b503-17e70f5d48cd">

**Expected behavior**

**Environment**
- Walrus version: main 4f06127b541a926b603ebff57960d887a8bb7264
- UI version: dev-b0e7988

**Additional context**

**Comment by thxCode** [comment]
https://github.com/walrus-catalog/terraform-aws-rds-mysql/pull/8
https://github.com/walrus-catalog/terraform-aws-rds-postgresql/pull/8
https://github.com/walrus-catalog/terraform-alicloud-rds-mysql/pull/7
https://github.com/walrus-catalog/terraform-alicloud-rds-postgresql/pull/7

the root cause is terraform ternary op expression needs; both results are the same type.

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main bd8b2f4560a522fcfb061a081817869f1a088f3a
- UI version: dev-4d5abee
- Template version: v0.3.0

**Test Result:** pass
